### ISSUE TITLE
Unexpected Error in MethodChannelGal

### ISSUE THREAD

**Issue by bishal-rumba007** [natsuk4ze/gal#231] opened 2024-08-01 06:48 UTC
### Did you check the documentation and it did not help?

- [X] I have read the [README](https://github.com/natsuk4ze/gal/blob/main/README.md)
- [X] I have searched the [existing documentation](https://github.com/natsuk4ze/gal/wiki)
- [X] I have searched the [existing answer](https://github.com/natsuk4ze/gal/discussions)
- [X] I have read the [contribution guide](https://github.com/natsuk4ze/gal/blob/main/CONTRIBUTING.md)

### Overview

An unexpected error occurs when trying to invoke a method via the MethodChannelGal class. The error trace indicates that an issue arises within the _invokeMethod method and subsequently affects the putVideo method, which is used to save a video to the gallery.

Error Trace:
#0      MethodChannelGal._invokeMethod (package:gal/src/gal_method_channel.dart:16:7)
I/flutter (25342): <asynchronous suspension>
I/flutter (25342): #1      MethodChannelGal.putVideo (package:gal/src/gal_method_channel.dart:27:5)
I/flutter (25342): <asynchronous suspension>
I/flutter (25342): #2      _PreviewScreenState._saveVideoToGallery (package:job_portal_app/src/video/presentation/screens/preview_screen.dart:41:7)
I/flutter (25342): <asynchronous suspension>
I/flutter (25342): [GalException/UNEXPECTED]: An unexpected error has occurred.

### Steps to reproduce

1. Call the _saveVideoToGallery method from the _PreviewScreenState class.
2. This method attempts to use MethodChannelGal.putVideo to save a video.
3. Observe the error that occurs, which is captured in the error trace above.

### Code sample

  Future<void> _saveVideoToGallery() async {
    try {
      await Gal.putVideo(widget.videoPath!);
    } catch (e) {
      debugPrint(e.toString());
    }
  }
  
  given that, widget.videoPath is : /data/user/0/com.example.sample_app/cache/REC8214881138209763913.temp

### Environment

[√] Flutter (Channel stable, 3.22.3, on Microsoft Windows [Version 10.0.19045.4651], locale en-US)
    • Flutter version 3.22.3 on channel stable at C:\Users\bishal\dev\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b0850beeb2 (2 weeks ago), 2024-07-16 21:43:41 -0700
    • Engine revision 235db911ba
    • Dart version 3.4.4     
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at C:\Users\Dham Bhattarai\AppData\Local\Android\sdk    
    • Platform android-34, build-tools 35.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2024.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.11+0--11852314)

[√] VS Code (version 1.91.1)
    • VS Code at C:\Users\bishal\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.92.0

[√] Connected device (4 available)
    • Redmi Note 9 Pro (mobile) • 227fc6e • android-arm64  • Android 12 (API 31)
    • Windows (desktop)         • windows • windows-x64    • Microsoft Windows [Version 10.0.19045.4651]
    • Chrome (web)              • chrome  • web-javascript • Google Chrome 127.0.6533.73
    • Edge (web)                • edge    • web-javascript • Microsoft Edge 127.0.2651.74

[√] Network resources
    • All expected network resources are available.

### Logs

I/flutter (25342): /data/user/0/com.example.sample_app/cache/REC8214881138209763913.temp
I/flutter (25342): #0      MethodChannelGal._invokeMethod (package:gal/src/gal_method_channel.dart:16:7)
I/flutter (25342): <asynchronous suspension>
I/flutter (25342): #1      MethodChannelGal.putVideo (package:gal/src/gal_method_channel.dart:27:5)
I/flutter (25342): <asynchronous suspension>
I/flutter (25342): #2      _PreviewScreenState._saveVideoToGallery (package:sample_app/src/video/presentation/screens/preview_screen.dart:41:7)

**Comment by natsuk4ze** [comment] 2024-08-01 07:10
@bishal-rumba007 
The file name `.temp` appears to be the cause. You need the extension of the video file.

**Comment by SteelTitan247** [comment] 2024-08-06 08:51
One of the solutions is to rename the file with mp4 extension. By renaming the file using this function fixed my issue:

  ```
Future<String> renameFile(String tempPath) async {
    final Directory directory = Directory(tempPath).parent;
    final String newPath = '${directory.path}/${DateTime.now().millisecondsSinceEpoch}.mp4';
    try {
      final File tempFile = File(tempPath);
      final File newFile = tempFile.renameSync(newPath);
      return newFile.path;
    } catch (e) {
      debugPrint("Error in renaming file in camera page: $e");
      return "";
    }
  }
```

**Comment by bishal-rumba007** [comment] 2024-08-07 10:59
> @bishal-rumba007 The file name `.temp` appears to be the cause. You need the extension of the video file like mp4.

@natsuk4ze @SteelTitan247 
I have found the issue to be using a .temp file directly, so as you have mentioned renaming the file works!
`  Future<String> _renameTempFile(String tempFilePath) async {
    final tempFile = File(tempFilePath);
    if (await tempFile.exists()) {
      // Define the new file path with a proper extension
      final newFilePath = tempFilePath.replaceAll(RegExp(r'\.temp$'), '.mp4');
      // Copy the file to the new path with the new extension
      final newFile = await tempFile.copy(newFilePath);
      return newFile.path;
    } else {
      throw const FileSystemException(
          "The file does not exist at the specified path.");
    }
  }`

**Comment by natsuk4ze** [comment] 2024-08-07 11:07
YES. It is an error if you do not use an extension that the OS can recognise as a media file.
Resolved, close this issue 🙆‍♀️

**Closed by natsuk4ze** 2024-08-07 11:07 UTC
Labels: 💬 waiting for response
